### ISSUE TITLE
breakpad does not compile on Ubuntu 18.04.2 LTS (Bionic)

### ISSUE THREAD

**Issue by johannesthoma** [couchbaselabs/breakpad#3]
Hi,

I tried to compile breakpad on Ubuntu 18.04.2 LTS (Bionic) and
got compilation errors. The reason was that the `struct ucontext`
type is called `struct ucontext_t` in the sys/ucontext.h header
of the 18.04.2 headers.

Changing struct ucontext to struct ucontext_t solves the problem,
it appears to work normally now. I can send a patch but I don't know
if it would break compilation on other systems (it probably will).

What would you suggest? Probably some compat header? configure
check?

Other than that, thanks a lot for the minidump-2-core utility, we use
it for analyzing WinDRBD (www.github.com/LINBIT/WinDRBD) crash
dumps with gdb.

Best regards,

- Johannes
